name: checkbox20
summary: Checkbox runtime and public providers
description: "Checkbox runtime and public providers"
version: '1.14.dev'
grade: stable

base: core20

# Don't forget to add a new slot if a new provider part is added in the parts
# section below.
slots:
  provider-resource:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-resource
  provider-checkbox:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-checkbox
  provider-snappy:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-snappy
  provider-ipdt:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-ipdt
  provider-docker:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-docker
  provider-tpm2:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-tpm2
  provider-engineering-tests:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-engineering-tests
  provider-sru:
    interface: content
    read:
      - $SNAP/providers/plainbox-provider-sru
  provider-edgex:
    interface: content
    read:
      - $SNAP/providers/checkbox-provider-edgex
  checkbox-runtime:
    interface: content
    read:
      - /

parts:
################################################################################
# Upstream: https://kernel.ubuntu.com/git/hwe/fwts.git/plain/snapcraft.yaml
  fwts:
    source-tag: ""
    source-depth: 1
    plugin: autotools
    source: git://kernel.ubuntu.com/hwe/fwts
    stage-packages:
      - libfdt1
      - libbsd0
      - libpci3
    build-packages:
      - gcc
      - make
      - autoconf
      - automake
      - libtool
      - libjson-c-dev
      - flex
      - bison
      - dh-autoreconf
      - libglib2.0-dev
      - libfdt-dev
      - libbsd-dev
################################################################################
# Upstream: https://kernel.ubuntu.com/git/cking/stress-ng.git/plain/snap/snapcraft.yaml
  stress-ng:
    source-tag: ""
    source-depth: 1
    plugin: make
    source: git://kernel.ubuntu.com/cking/stress-ng
    make-parameters:
      - STATIC=1
    build-packages:
      - gcc
      - make
      - zlib1g-dev
      - libbsd-dev
      - libattr1-dev
      - libgcrypt20-dev
      - libkeyutils-dev
      - libapparmor-dev
      - libaio-dev
      - libcap-dev
      - libsctp-dev
    after: [fwts]
################################################################################
# Upstream: https://kernel.ubuntu.com/git/cking/snapcraft-snaps.git/tree/acpica/snapcraft.yaml
  acpi-tools:
    source-tag: ""
    source-depth: 1
    plugin: make
    source: https://github.com/acpica/acpica.git
    build-packages:
      - gcc
      - make
      - bison
      - flex
    prime:
      - usr/bin/
    after: [stress-ng]
################################################################################
  checkbox-support:
    source-tag: ""
    source-depth: 1
    plugin: python
    source: git://git.launchpad.net/checkbox-support
    stage-packages:
      # actual requirements
      - python3-requests-unixsocket
      - python3-systemd
      # added to stage python:
      - libpython3-stdlib
      - libpython3.8-stdlib
      - libpython3.8-minimal
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - python3-minimal
      - python3-distutils
      - python3-pkg-resources
      - python3.8-minimal
    python-packages:
      - pynmea2
    after: [acpi-tools]
    stage:
      - -pyvenv.cfg
      - -bin/activate*
      - -**/RECORD
      - -**/__pycache__
    build-environment:
      - PYTHONPATH: $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages:$PYTHONPATH
################################################################################
  checkbox-ng:
    source-tag: ""
    source-depth: 1
    plugin: python
    source: git://git.launchpad.net/checkbox-ng
    build-packages:
      - zlib1g-dev
      - build-essential
    stage-packages:
      - python3-crypto
      - python3-markupsafe
      - python3-jinja2
      - python3-padme
      - python3-requests-oauthlib
      - python3-urwid
      - python3-xlsxwriter
      # added to stage python:
      - libpython3-stdlib
      - libpython3.8-stdlib
      - libpython3.8-minimal
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - python3-minimal
      - python3-distutils
      - python3-pkg-resources
      - python3.8-minimal
    python-packages:
      - tqdm
    after: [checkbox-support]
    stage:
      - -pyvenv.cfg
      - -bin/activate*
      - -**/RECORD
      - -**/__pycache__
    build-environment:
      - PYTHONPATH: $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages:$PYTHONPATH
################################################################################
  plainbox-provider-resource:
    source-tag: ""
    source-depth: 1
    plugin: python
    source: git://git.launchpad.net/plainbox-provider-resource
    stage-packages:
      - cpu-checker
      - dpkg
      - dmidecode
      - libjson-xs-perl
      - pciutils
      - python3-requests-unixsocket
      - smartmontools
    override-build: |
      cd src && autoreconf -i && cd -
      provider_path=""
      provider_stage_dir="$SNAPCRAFT_STAGE/providers"
      if [ -d "$provider_stage_dir" ]; then
        for d in "$provider_stage_dir"/*/ ; do
          provider_path="$provider_path:$d"
        done
      fi
      export PROVIDERPATH="$provider_path"
      export PYTHONPATH="$PYTHONPATH:$SNAPCRAFT_STAGE/lib/python3.8/site-packages"
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-resource --root=${SNAPCRAFT_PART_INSTALL}
    build-packages:
      - autoconf
      - automake
      - libnl-3-dev
      - libnl-genl-3-dev
      - pkg-config
    after: [checkbox-ng]
################################################################################
  plainbox-provider-checkbox:
    source-tag: ""
    source-depth: 1
    plugin: python
    source: git://git.launchpad.net/plainbox-provider-checkbox
    stage-packages:
      - bc
      - bluez-tests
      - bonnie++
      - cryptsetup-bin
      - dbus
      - dmidecode
      - dmsetup
      - ethtool
      - fswebcam
      - gir1.2-cheese-3.0
      - gir1.2-clutter-1.0
      - gir1.2-gst-plugins-base-1.0
      - gir1.2-gudev-1.0
      - gstreamer1.0-tools
      - gstreamer1.0-pulseaudio
      - try: [hdapsd] # optional as not available for arm
      - hdparm
      - i2c-tools
      - ipmitool
      - iperf
      - iperf3
      - iw
      - jq
      - kmod
      - libasound2
      - libcap2-bin
      - libfdt1
      - lshw
      - mesa-utils
      - mokutil
      - net-tools
      - nmap
      - nux-tools
      - nvme-cli
      - obexftp
      - parted
      - pciutils
      - pulseaudio-utils
      - pyotherside
      - python3-dbus
      - python3-evdev
      - python3-gi
      - python3-pil
      - python3-psutil
      - python3-pyqrcode
      - python3-yaml
      - python3-zbar
      - qml-module-qtquick-controls
      - qml-module-qtquick-layouts
      - qmlscene
      - smartmontools
      - usbutils
      - util-linux
      - uuid-runtime
      - wget
      - wmctrl
    build-packages:
      - libasound2-dev
      - libcap-dev
    after: [plainbox-provider-resource]
    override-build: |
      provider_path=""
      provider_stage_dir="$SNAPCRAFT_STAGE/providers"
      if [ -d "$provider_stage_dir" ]; then
        for d in "$provider_stage_dir"/*/ ; do
          provider_path="$provider_path:$d"
        done
      fi
      export PROVIDERPATH="$provider_path"
      export PYTHONPATH="$PYTHONPATH:$SNAPCRAFT_STAGE/lib/python3.8/site-packages"
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-checkbox --root=${SNAPCRAFT_PART_INSTALL}
################################################################################
  plainbox-provider-ipdt:
    source-tag: ""
    source-depth: 1
    plugin: python
    source: git://git.launchpad.net/plainbox-provider-ipdt
    stage-packages:
      - util-linux
    after: [plainbox-provider-checkbox]
    override-build: |
      provider_path=""
      provider_stage_dir="$SNAPCRAFT_STAGE/providers"
      if [ -d "$provider_stage_dir" ]; then
        for d in "$provider_stage_dir"/*/ ; do
          provider_path="$provider_path:$d"
        done
      fi
      export PROVIDERPATH="$provider_path"
      export PYTHONPATH="$PYTHONPATH:$SNAPCRAFT_STAGE/lib/python3.8/site-packages"
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-ipdt --root=${SNAPCRAFT_PART_INSTALL}
################################################################################
  plainbox-provider-docker:
    source-tag: ""
    source-depth: 1
    plugin: python
    source: git://git.launchpad.net/plainbox-provider-docker
    after: [plainbox-provider-ipdt]
    override-build: |
      provider_path=""
      provider_stage_dir="$SNAPCRAFT_STAGE/providers"
      if [ -d "$provider_stage_dir" ]; then
        for d in "$provider_stage_dir"/*/ ; do
          provider_path="$provider_path:$d"
        done
      fi
      export PROVIDERPATH="$provider_path"
      export PYTHONPATH="$PYTHONPATH:$SNAPCRAFT_STAGE/lib/python3.8/site-packages"
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-docker --root=${SNAPCRAFT_PART_INSTALL}
################################################################################
  plainbox-provider-tpm2:
    source-tag: ""
    source-depth: 1
    plugin: python
    source: git://git.launchpad.net/plainbox-provider-tpm2
    stage-packages:
      - tpm2-tools
    after: [plainbox-provider-docker]
    override-build: |
      provider_path=""
      provider_stage_dir="$SNAPCRAFT_STAGE/providers"
      if [ -d "$provider_stage_dir" ]; then
        for d in "$provider_stage_dir"/*/ ; do
          provider_path="$provider_path:$d"
        done
      fi
      export PROVIDERPATH="$provider_path"
      export PYTHONPATH="$PYTHONPATH:$SNAPCRAFT_STAGE/lib/python3.8/site-packages"
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-tpm2 --root=${SNAPCRAFT_PART_INSTALL}
################################################################################
  plainbox-provider-sru:
    source-tag: ""
    source-depth: 1
    plugin: python
    source: git://git.launchpad.net/plainbox-provider-sru
    after: [plainbox-provider-tpm2]
    override-build: |
      provider_path=""
      provider_stage_dir="$SNAPCRAFT_STAGE/providers"
      if [ -d "$provider_stage_dir" ]; then
        for d in "$provider_stage_dir"/*/ ; do
          provider_path="$provider_path:$d"
        done
      fi
      export PROVIDERPATH="$provider_path"
      export PYTHONPATH="$PYTHONPATH:$SNAPCRAFT_STAGE/lib/python3.8/site-packages"
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-sru --root=${SNAPCRAFT_PART_INSTALL}
################################################################################
  checkbox-provider-edgex:
    source-tag: ""
    source-depth: 1
    plugin: python
    source: git://git.launchpad.net/checkbox-provider-edgex
    stage-packages:
      - curl
    after: [plainbox-provider-sru]
    override-build: |
      provider_path=""
      provider_stage_dir="$SNAPCRAFT_STAGE/providers"
      if [ -d "$provider_stage_dir" ]; then
        for d in "$provider_stage_dir"/*/ ; do
          provider_path="$provider_path:$d"
        done
      fi
      export PROVIDERPATH="$provider_path"
      export PYTHONPATH="$PYTHONPATH:$SNAPCRAFT_STAGE/lib/python3.8/site-packages"
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/checkbox-provider-edgex --root=${SNAPCRAFT_PART_INSTALL}
################################################################################
  plainbox-provider-snappy:
    source-tag: ""
    source-depth: 1
    plugin: python
    source: git://git.launchpad.net/plainbox-provider-snappy
    after: [checkbox-provider-edgex]
    override-build: |
      provider_path=""
      provider_stage_dir="$SNAPCRAFT_STAGE/providers"
      if [ -d "$provider_stage_dir" ]; then
        for d in "$provider_stage_dir"/*/ ; do
          provider_path="$provider_path:$d"
        done
      fi
      export PROVIDERPATH="$provider_path"
      export PYTHONPATH="$PYTHONPATH:$SNAPCRAFT_STAGE/lib/python3.8/site-packages"
      python3 manage.py validate
      python3 manage.py build
      python3 manage.py install --layout=relocatable --prefix=/providers/plainbox-provider-snappy --root=${SNAPCRAFT_PART_INSTALL}
################################################################################
  # This module is a dependency for the job gpio/gpiomem_loopback_pairs_{model}
  # in plainbox-provider-snappy only available in pypi and so can't be addded
  # to stage-packages
  # rpi-support-libs:
  #   plugin: python
  #   python-packages:
  #     - RPi.GPIO
  #     - picamera
  #   build-environment:
  #     - READTHEDOCS: 'True'
  # rpi-ppa:
  #   plugin: nil
  #   override-pull: |
  #     sudo add-apt-repository ppa:ubuntu-raspi2/ppa
  #     sudo apt-get update
  #   build-packages:
  #     - software-properties-common
  # rpi-support-binaries:
  #   after: [rpi-ppa]
  #   plugin: nil
  #   stage-packages:
  #     - try: [libraspberrypi0] # optional as only available on arm
  #   organize:
  #     usr/lib/lib*.so: usr/lib/$SNAPCRAFT_ARCH_TRIPLET/
################################################################################
  lk-boot-env:
    plugin: nil
    source: .
    override-pull: |
      snapcraftctl pull
      wget https://github.com/snapcore/snapd/raw/master/include/lk/snappy_boot_v1.h
      wget https://raw.githubusercontent.com/kubiko/if6640-gadget/18/snap-boot-sel/lk-boot-env.c
    build-packages:
      - wget
      - on amd64 to armhf:
        - gcc-arm-linux-gnueabihf:amd64
      - on amd64 to arm64:
        - gcc-aarch64-linux-gnu:amd64
    override-build: |
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin
      if [ "${SNAPCRAFT_ARCH_TRIPLET}" = "arm-linux-gnueabihf" ]; then
          arm-linux-gnueabihf-gcc lk-boot-env.c -I/usr/include/ -Iapp/aboot -o ${SNAPCRAFT_PART_INSTALL}/bin/lk-boot-env
      elif [ "${SNAPCRAFT_ARCH_TRIPLET}" = "aarch64-linux-gnu" ]; then
          aarch64-linux-gnu-gcc lk-boot-env.c -I/usr/include/ -Iapp/aboot -o ${SNAPCRAFT_PART_INSTALL}/bin/lk-boot-env
      else
          # native build
          gcc lk-boot-env.c -I/usr/include/ -Iapp/aboot -o ${SNAPCRAFT_PART_INSTALL}/bin/lk-boot-env
      fi
################################################################################
  parts-meta-info:
    plugin: nil
    override-build: |
      snapcraftctl build
      echo $PWD
      ls -1 -d ../../*
      for p in `ls -d ../../*`; do
          if [ -d $p/src ]; then
            (cd $p/src
                if [ -d $p/src/.git ]; then
                    (echo `basename $p`\: && git show --pretty=format:"%h%d %aN %ci%n%s%n" -q ; echo ) >> $SNAPCRAFT_PART_INSTALL/parts_meta_info
                fi # for additional `source-type` support, elif them here
            )
          fi
      done
    after: [checkbox-provider-edgex]
################################################################################
  common-config:
    plugin: dump
    source: config/
