name: create-checkbox-canary-test-job
description: "Create job.yaml for Checkbox canary tests"
inputs:
  queue:
    required: true
  data_source:
    required: true
  checkbox_runtime:
    required: true
  checkbox_track:
    required: true
outputs:
  job:
    description: "The text for the Checkbox canary test YAML"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cat << JOB_EOF > job.yaml
        job_queue : ${{ inputs.queue }}
        global_timeout: 3600
        output_timeout: 1800
        provision_data:
          ${{ inputs.data_source }}
        test_data:
          test_cmds: |
            set -x
            set -e

            # prepare Controller Machine
            sudo add-apt-repository -y ppa:checkbox-dev/edge
            sudo apt-get -qq update
            sudo DEBIAN_FRONTEND=noninteractive apt-get -qq install -y python-cheetah git checkbox-ng

            # get the tools necessary to prepare the target device for testing
            git -C hwcert-jenkins-tools pull -q || (rm -rf hwcert-jenkins-tools && git clone https://github.com/canonical/hwcert-jenkins-tools.git)

            export PATH=$PATH:hwcert-jenkins-tools/scriptlets

            echo "Installing checkbox in agent container"
            git clone --filter=tree:0 https://github.com/canonical/checkbox.git > /dev/null
            hwcert-jenkins-tools/version-published/checkout_to_version.py ~/checkbox "$CHECKBOX_VERSION"
            (cd checkbox/checkbox-ng; sudo python3 setup.py install > /dev/null)
            sudo rm -rf checkbox

            # run the canary test plan
            PYTHONUNBUFFERED=1 checkbox-cli control $DEVICE_IP canary.launcher
            EXITCODE=$?
        JOB_EOF
        cat job.yaml