#!/bin/bash
set -x
usage() {
cat << EOF
usage: $0 options [PLAIN]

    options:
        -h|--help print this message

    PLAIN:
        could be somerville_sanity_before_suspend, somerville_sanity_after_suspend, stress-suspend-30-cycles-with-reboots-automated, sru ... etc
        hint: any plan in /usr/share/plainbox-provider-*/units could be used here.
EOF
exit 1
}

while [ $# -gt 0 ]
do
    case "$1" in
        -h | --help)
            usage 0
            exit 0
            ;;
        *)
            PLAIN=$1
            echo "== you selected $PLAIN =="
       esac
       shift
done

cat <<EOF > $HOME/generated_launcher
#!/usr/bin/env checkbox-cli
[launcher]
launcher_version = 1

[config]
config_filename = /usr/lib/prepare-checkbox-sanity/checkbox.conf

[test plan]
unit = com.canonical.certification::$PLAIN
forced = yes

[test selection]
forced = yes
exclude = .*usb/storage-preinserted .*suspend/usb_storage_preinserted_after_suspend .*stress/cpu_stress_ng_test .*disk/disk_stress_.*

[ui]
type = silent
EOF

checkbox-cli launcher $HOME/generated_launcher
