name: Fling a checkbox job with Testflinger

on:
    push:
        branches: [test-action-fling-test]
    workflow_dispatch:

jobs:
  checkbox-canary-test:
    runs-on: [self-hosted, testflinger]
    strategy:
      fail-fast: false
      matrix:
        include:
          - checkbox_runtime: checkbox16
            data_source: "distro: xenial"
            checkbox_track: uc16
            arch: amd64
            queue: hp-elitebook-850-g7-notebook-pc
          - checkbox_runtime: checkbox22
            data_source: "distro: jammy"
            checkbox_track: uc22
            arch: amd64
            queue: hp-elitebook-850-g7-notebook-pc
          - checkbox_runtime: checkbox22
            data_source: "url: http://cdimage.ubuntu.com/ubuntu-core/22/dangerous-stable/current/ubuntu-core-22-arm64+raspi.img.xz"
            checkbox_track: uc22
            arch: arm64
            queue: rpi4b4g

    steps:
    - name: Checkout checkbox monorepo
      uses: actions/checkout@v4

    - name: Create job
      id: create-job
      uses: ./.github/actions/create-checkbox-canary-test-job
      with:
        queue: ${{ matrix.queue }}
        data_source: ${{ matrix.data_source }}
        checkbox_runtime: ${{ matrix.checkbox_runtime }}
        checkbox_track: ${{ matrix.checkbox_track }}
    
    - name: Verify job
      shell: bash
      run:
        cat ${{ steps.create-job.outputs.job }}

    - name: Submit job
      uses: canonical/certification-github-workflows/.github/actions/fling-test@testflinger-action-incremental
      with:
        dry-run: false
        poll: true
        job: ${{ steps.create-job.outputs.job }}
