name: PR test with testflinger

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
      - edited

jobs:
  testflinger-pr-test:
    runs-on: [self-hosted, testflinger]
    strategy:
      matrix:
        include:
          - checkbox_runtime: checkbox16
            checkbox_data_source: "distro: xenial"
            checkbox_track: uc16
            arch: amd64
            queue: hp-elitebook-850-g7-notebook-pc
          - checkbox_runtime: checkbox22
            checkbox_data_source: "distro: jammy"
            checkbox_track: uc22
            arch: amd64
            queue: hp-elitebook-850-g7-notebook-pc
          - checkbox_runtime: checkbox22
            checkbox_data_source: "url: http://cdimage.ubuntu.com/ubuntu-core/22/dangerous-stable/current/ubuntu-core-22-arm64+raspi.img.xz"
            checkbox_track: uc22
            arch: arm64
            queue: rpi4b4g
    defaults:
      run:
        working-directory: tools/canary/
    steps:
    - name: Checkout checkbox monorepo
      uses: actions/checkout@v3
    - name: Install testflinger
      run: |
        sudo snap install testflinger-cli
    - name: Test testflinger connection
      run: |
        nc -vz testflinger.canonical.com 443
    - name: Submit job to testflinger
      env:
        CHECKBOX_RUNTIME: ${{ matrix.checkbox_runtime }}
        CHECKBOX_DATA_SOURCE: ${{ matrix.checkbox_data_source }}
        CHECKBOX_TRACK: ${{ matrix.checkbox_track }}
        ARCH: ${{ matrix.arch }}
        QUEUE: ${{ matrix.queue }}
      run: |
        # produce job.yaml
        ./canary.sh
        cat job.yaml
        exit 0
        JOB_ID=$(testflinger submit -q job.yaml)
        echo "JOB_ID: $JOB_ID"
        testflinger poll $JOB_ID

        TEST_STATUS=$(testflinger results $JOB_ID | jq -er .test_status)
        echo "Test exit status: $TEST_STATUS"
        exit $TEST_STATUS
