name: PR test with testflinger

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
      - edited

jobs:
  testflinger-pr-test:
    runs-on: [self-hosted, testflinger]
    defaults:
      run:
        working-directory: tools/canary/
    steps:
    - name: Checkout checkbox monorepo
      uses: actions/checkout@v3
    - name: info setup
      run: |
        echo "Testing testflinger setup"
    - name: install testflinger
      run: |
        sudo snap install testflinger-cli
    - name: test installation
      run: |
        testflinger-cli -h
    - name: try curl testflinger
      run: |
        curl https://testflinger.canonical.com
        nc -vz testflinger.canonical.com 443
    - name: try list queues
      run: |
        testflinger-cli list-queues
    - name: Submit job to testflinger
      run: |
        JOB_ID=$(testflinger submit -q example_job.yaml)
        testflinger poll $JOB_ID
