name: PR test with testflinger

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
      - edited

jobs:
  testflinger-pr-test:
    runs-on: [self-hosted, testflinger]
    defaults:
      run:
        working-directory: tools/canary/
    steps:
    - name: Checkout checkbox monorepo
      uses: actions/checkout@v3
    - name: Install testflinger
      run: |
        sudo snap install testflinger-cli
    - name: Test testflinger connection
      run: |
        nc -vz testflinger.canonical.com 443
    - name: Submit job to testflinger
      run: |
        JOB_ID=$(testflinger submit -q canary_validation.yaml)
        echo "JOB_ID: $JOB_ID"
        testflinger poll $JOB_ID

        TEST_STATUS=$(testflinger results $JOB_ID | jq -er .test_status)
        echo "Test exit status: $TEST_STATUS"
        exit $TEST_STATUS