name: Fling a checkbox job with Testflinger

on:
    push:
        branches: [test-action-fling-test]
    workflow_dispatch:

jobs:
  testflinger-pr-test:
    runs-on: [self-hosted, testflinger]
    steps:
    - name: Checkout checkbox monorepo
      uses: actions/checkout@v3
    - name: Submit job to testflinger
      uses: canonical/certification-github-workflows/.github/actions/fling-test@testflinger-action-incremental
      with:
        job_queue: rpi4b1g-001
        test_data: |
          test_cmds: |
            ls -alR
